# For first manual deployment:  INITIALIZE_RAG=true docker-compose up -d

# To upload the docs with CLI:
# curl -X POST "http://server_ip:9000/upload/document" \
#     -H "accept: application/json" \
#     -H "Content-Type: multipart/form-data" \
#     -F "file=@/path/to/your/document.pdf" \
#     -F "folder=your/folder/path"
# And then trigger the processing:
# curl -X POST "http://server_ip:9000/process/documents"

## Trigger github webhook manually:
# curl -X POST http://localhost:9000/webhook \
#  -H "X-Hub-Signature-256: sha256=$(echo -n "AtlantiumTechnologies1625" | openssl dgst -binary -sha256 | xxd -p -c 256)" \
#  -d '{"ref":"refs/heads/master"}'
## This should trigger the update process and one should see similar logs as a manual update.

## General commands:
# Remove all containers
# docker rm -f $(docker ps -a -q)
# Remove all:
# docker system prune --all --volumes --force
# Get the  last 100 lines of logs:
# docker logs atlantium_llm-web-app-1 -f --tail=100

### Normal Operation Sequence:
# git clone https://github.com/kertser/Atlantium_LLM.git
# cd Atlantium_LLM
# cp .env.example .env
# chmod +x deploy.sh install_requirements.sh
# sudo ./deploy.sh --init
# The web app will be available at http://server_ip:9000

version: '3.8'

services:
  web-app-gpu:
    container_name: ${CONTAINER_NAME:-atlantium_llm-web-app-1}
    environment:
      - PYTHONIOENCODING=utf-8
      - USE_CPU=0
      - INITIALIZE_RAG=${INITIALIZE_RAG:-false}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "9000:9000"
    volumes:
      - raw_docs:/app/Raw Documents
      - rag_data:/app/RAG_Data
      - logs:/app/logs
      - ./update_rag.sh:/app/scripts/update_rag.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - gpu

  web-app-cpu:
    container_name: ${CONTAINER_NAME:-atlantium_llm-web-app-1}
    environment:
      - PYTHONIOENCODING=utf-8
      - USE_CPU=1
      - INITIALIZE_RAG=${INITIALIZE_RAG:-false}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=cpu
    ports:
      - "9000:9000"
    volumes:
      - raw_docs:/app/Raw Documents
      - rag_data:/app/RAG_Data
      - logs:/app/logs
      - ./update_rag.sh:/app/scripts/update_rag.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - cpu

volumes:
  raw_docs:
    driver: local
  rag_data:
    driver: local
  logs:
    driver: local